# Don't print a new line at the start of the prompt
add_newline = false

[line_break]
disabled = true

# Replace the "❯" symbol in the prompt with "➜"
[character]
symbol = "➜"
error_symbol = "✗"
use_symbol_for_status = true

[conda]
style = "dimmed green"

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[hostname]
ssh_only = false
prefix = "⟪ "
suffix = " ⟫"

[username]
show_always = true
style_user = "bold blue"

